/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionsSchedule: typeof import('./src/components/dialog/actions-schedule/index.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Image: typeof import('primevue/image')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
  }
}
