version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://localhost:5000
    networks:
      - minha-rede

  server:
    build:
      context: ./server/ScheduleBlue/
      dockerfile: Dockerfile.dotnet
    ports:
      - "5000:80"
    networks:
      - minha-rede
      
networks:
  minha-rede: